### PR TITLE
Adds WATCHERS @mention by labels

### PR DESCRIPTION
**Pull request by hiimbex**
adds a `watcher-notifier` that tags based off a `WATCHERS` file that imitates the structure of an `OWNERS` file. There's probably some duplicated code in `watcher-notifier` and `owner-notifier` that could potentially be modularized? Thoughts? I did modularize `changes.js` to make sense for both variable name wise. It also includes `event` -> `context` and Integration -> App

Do you think that we should also `robot.on('issues.labeled', notifyWatchers);` or is this project more pull request centered?

Also, not sure if the `WATCHERS` file is actually optional right now? It softly errors, but wasn't sure the best way to accomplish that. Also would love feedback on documentation updates!

cc/ @bkeepers

### CODE REVIEW

**Comment by hiimbex** [comment]
@bkeepers I was going through my several open PRs on probot stuff (😂) and I was thinking about whether this actually belonged in owners or whether it should be it's own plugin like watch-labels with a `WATCH_LABELS` file?

I don't see this as having a _ton_ of use cases, but I could see it as being worth having somewhere at least. For example, I would totally watch like help wanted labels in probot! Let me know what you think, I'm happy to throw this into its own plugin if you think that's best!

**Comment by bkeepers** [comment]
> I was going through my several open PRs on probot stuff (😂) …

Yeah, sorry, I have a bunch of reviews to catch up on.

>  I was thinking about whether this actually belonged in owners or whether it should be it's own plugin like watch-labels…

Yeah, I think you're right that it might belong in its own plugin.

**Comment by bkeepers** [comment]
> Yeah, I think you're right that it might belong in its own plugin.

Closing this PR since it's out of date and ☝️

**Comment by hiimbex** [comment]
what a throwback!!

**Pull request closed without merging**
